[tool.poetry]
name = "comparar_fundos_br"
version = "0.1.0"
description = ""
authors = ["Rafael Rodrigues <rafael.rafarod@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.4.3"
seaborn = "^0.11.2"
requests = "^2.28.1"
yfinance = "^0.1.74"
DateTime = "^4.5"
pytrendseries = "^0.1.9"
tesouro-direto-br = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"